plugins {
    id 'com.android.application'
    id 'kotlin-android'
}

android {
    namespace "com.openvins.android"
    compileSdk 30

    defaultConfig {
        applicationId "com.openvins.android"
        minSdkVersion 21
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        externalNativeBuild {
            cmake {
                cppFlags "-std=c++11 -frtti -fexceptions"
                abiFilters 'x86', 'x86_64', 'arm64-v8a' // 'armeabi-v7a',
                arguments "-DOpenCV_DIR=" + project(':thirdparty:opencv').projectDir.absolutePath + "/native",
                        "-DBOOST_DIR=" + project(':thirdparty:boost').projectDir.absolutePath,
                        "-DEIGEN3_DIR=" + project(':thirdparty:eigen3').projectDir.absolutePath,
                        "-DANDROID_ARM_NEON=ON"
            }
        }
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    externalNativeBuild {
        cmake {
            path "src/main/cpp/CMakeLists.txt"
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"
    implementation 'androidx.core:core-ktx:1.2.0'
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'com.google.android.material:material:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'
    implementation project(':thirdparty:opencv')
    implementation project(':thirdparty:opencv')
    //implementation project(':open_vins')
}